export const products = [
    {
        id: 101,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Broccoli',
        price: 80,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 20,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/broccoli.jpg'
    },
    {
        id: 102,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Cabbage',
        price: 60,
        currency: 'Tk',
        unit: 'pcs',
        discountInPercent: 20,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/cabbage.jpg'
    },
    {
        id: 103,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Local Carrot',
        price: 40,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 18,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/carrot.jpg'
    },
    {
        id: 104,
        category: 'vegetables',
        subCategory: '',
        name: 'Local Cucumber',
        price: 60,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/cucumber.jpg'
    },
    {
        id: 105,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Cauliflower',
        price: 80,
        currency: 'Tk',
        unit: 'pcs',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/cauliflower.jpg'
    },
    {
        id: 106,
        category: 'vegetables',
        subCategory: '',
        name: 'Potato Seasonal',
        price: 30,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/potato.jpg'
    },
    {
        id: 107,
        category: 'vegetables',
        subCategory: '',
        name: 'Local Onion',
        price: 40,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/onion.jpg'
    },
    {
        id: 108,
        category: 'vegetables',
        subCategory: '',
        name: 'Local Chili',
        price: 50,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 10,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/chili-local.jpg'
    },
    {
        id: 109,
        category: 'vegetables',
        subCategory: '',
        name: 'Bean Seed',
        price: 120,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 18,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/bean-seed.jpg'
    },
    {
        id: 110,
        category: 'vegetables',
        subCategory: '',
        name: 'Long Bean',
        price: 60,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 24,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/long-bean.jpg'
    },
    {
        id: 111,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Tomato',
        price: 40,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/tomato.jpg'
    },
    {
        id: 112,
        category: 'vegetables',
        subCategory: 'top',
        name: 'Motorshuti',
        price: 140,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/motorshuti.jpg'
    },
    {
        id: 113,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Radish',
        price: 30,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/radish.jpg'
    },
    {
        id: 114,
        category: 'vegetables',
        subCategory: 'popular',
        name: 'Red Radish',
        price: 35,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/red-radish.jpg'
    },
    {
        id: 115,
        category: 'vegetables',
        subCategory: 'top',
        name: 'Green Chili',
        price: 60,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/chili.jpg'
    },
    {
        id: 116,
        category: 'vegetables',
        subCategory: 'top',
        name: 'Green Peas',
        price: 90,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 20,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/peas.jpg'
    },
    {
        id: 117,
        category: 'vegetables',
        subCategory: '',
        name: 'Capsicum',
        price: 110,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 18,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/capsicum.jpg'
    },
    {
        id: 118,
        category: 'vegetables',
        subCategory: '',
        name: 'Zucchini',
        price: 80,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 18,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/vegetables/zucchini.jpg'
    },
    {
        id: 119,
        category: 'fruits',
        subCategory: 'top',
        name: 'Fresh Apple',
        price: 160,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 18,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/apple.jpg'
    },
    {
        id: 120,
        category: 'fruits',
        subCategory: 'top',
        name: 'Fresh Orange',
        price: 140,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 20,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/orange.jpg'
    },
    {
        id: 121,
        category: 'fruits',
        subCategory: '',
        name: 'Green Orange',
        price: 160,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/orange-green.jpg'
    },
    {
        id: 122,
        category: 'fruits',
        subCategory: '',
        name: 'Fresh Grape',
        price: 180,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/grape.jpg'
    },
    {
        id: 123,
        category: 'fruits',
        subCategory: '',
        name: 'Fresh Kiwi',
        price: 130,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 24,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/kiwi.jpg'
    },
    {
        id: 124,
        category: 'fruits',
        subCategory: 'top',
        name: 'Pomegranate',
        price: 180,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 20,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/pomegranate.jpg'
    },
    {
        id: 125,
        category: 'fruits',
        subCategory: 'top',
        name: 'Strawberry',
        price: 130,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 48,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/strawberry.jpg'
    },
    {
        id: 126,
        category: 'fruits',
        subCategory: 'top',
        name: 'Fresh Peach',
        price: 160,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 42,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/peach.jpg'
    },
    {
        id: 127,
        category: 'fruits',
        subCategory: 'recent',
        name: 'Fresh Mango',
        price: 180,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/mango.jpg'
    },
    {
        id: 128,
        category: 'fruits',
        subCategory: 'popular',
        name: 'Fresh Lemon',
        price: 120,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/lemon.jpg'
    },
    {
        id: 129,
        category: 'fruits',
        subCategory: '',
        name: 'Cherry',
        price: 150,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/cherry.jpg'
    },
    {
        id: 130,
        category: 'fruits',
        subCategory: '',
        name: 'Blueberry',
        price: 140,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/blueberry.jpg'
    },
    {
        id: 131,
        category: 'fruits',
        subCategory: 'recent',
        name: 'Pinapple',
        price: 80,
        currency: 'Tk',
        unit: 'pcs',
        discountInPercent: 26,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/pinapple.jpg'
    },
    {
        id: 132,
        category: 'fruits',
        subCategory: 'recent',
        name: 'Watermelon',
        price: 350,
        currency: 'Tk',
        unit: 'pcs',
        discountInPercent: 12,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/fruits/watermelon.jpg'
    },
    {
        id: 133,
        category: 'meat-fish',
        subCategory: '',
        name: 'Chicken',
        price: 180,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/chicken.jpg'
    },
    {
        id: 134,
        category: 'meat-fish',
        subCategory: '',
        name: 'Beef',
        price: 720,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/beef.jpg'
    },
    {
        id: 135,
        category: 'meat-fish',
        subCategory: '',
        name: 'Buffalo',
        price: 1040,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 30,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/buffalo.jpg'
    },
    {
        id: 136,
        category: 'meat-fish',
        subCategory: '',
        name: 'Mutton',
        price: 860,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 50,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/mutton.jpg'
    },
    {
        id: 137,
        category: 'meat-fish',
        subCategory: '',
        name: 'Camel',
        price: 1220,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 24,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/camel.jpg'
    },
    {
        id: 138,
        category: 'meat-fish',
        subCategory: '',
        name: 'Shrimp',
        price: 980,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/shrimp.jpg'
    },
    {
        id: 139,
        category: 'meat-fish',
        subCategory: '',
        name: 'Common Carp',
        price: 240,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 26,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/common-carp.jpg'
    },
    {
        id: 140,
        category: 'meat-fish',
        subCategory: '',
        name: 'Sprat',
        price: 460,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 12,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/sprat.jpg'
    },
    {
        id: 141,
        category: 'meat-fish',
        subCategory: '',
        name: 'Trout',
        price: 520,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/meat&fish/trout.jpg'
    },
    {
        id: 142,
        category: 'eggs',
        subCategory: '',
        name: 'Koyel Egg',
        price: 30,
        currency: 'Tk',
        unit: 'dzn',
        discountInPercent: 22,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/eggs/koyel-egg.jpg'
    },
    {
        id: 143,
        category: 'eggs',
        subCategory: '',
        name: 'Chicken Egg',
        price: 90,
        currency: 'Tk',
        unit: 'dzn',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/eggs/chicken-egg.jpg'
    },
    {
        id: 144,
        category: 'eggs',
        subCategory: '',
        name: 'Duck Egg',
        price: 120,
        currency: 'Tk',
        unit: 'dzn',
        discountInPercent: 26,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/eggs/duck-egg.jpg'
    },
    {
        id: 145,
        category: 'beverages',
        subCategory: '',
        name: 'Tea Leaf',
        price: 640,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 0,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/beverages/tea.jpg'
    },
    {
        id: 146,
        category: 'beverages',
        subCategory: 'popular',
        name: 'Coffe',
        price: 1280,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/beverages/coffe.jpg'
    },
    {
        id: 147,
        category: 'beverages',
        subCategory: 'recent',
        name: 'Green Tea',
        price: 890,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 26,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/beverages/green-tea.jpg'
    },
    {
        id: 148,
        category: 'spices',
        subCategory: 'recent',
        name: 'Clove',
        price: 820,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 12,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/spices/clove.jpg'
    },
    {
        id: 149,
        category: 'spices',
        subCategory: '',
        name: 'Cardamom',
        price: 960,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 26,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/spices/cardamom.jpg'
    },
    {
        id: 150,
        category: 'spices',
        subCategory: '',
        name: 'Mix Spice',
        price: 860,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/spices/mix-spice.jpg'
    },
    {
        id: 151,
        category: 'dried-fruits',
        subCategory: 'recent',
        name: 'Almond',
        price: 860,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/driedFruits/almond.jpg'
    },
    {
        id: 152,
        category: 'dried-fruits',
        subCategory: 'recent',
        name: 'Dates',
        price: 460,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 26,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/driedFruits/dates.jpg'
    },
    {
        id: 153,
        category: 'dried-fruits',
        subCategory: 'recent',
        name: 'Raisins',
        price: 580,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 12,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/driedFruits/raisins.jpg'
    },
    {
        id: 154,
        category: 'dried-fruits',
        subCategory: '',
        name: 'Cashew Nut',
        price: 980,
        currency: 'Tk',
        unit: 'Kg',
        discountInPercent: 16,
        addedToCart: 0,
        addedToFavorite: false,
        cartAddedTime: '',
        imageUrl: './images/driedFruits/cashew-nut.jpg'
    }
];